### ISSUE TITLE
Add an option to mark a configuration field as "display field"

### ISSUE THREAD

**Issue by vmalloc** [platzio/frontend#18]
In some cases the full name of a deployment might become too long to read, and thus quickly find in a long list of deployments.

It can be useful to have a specific config field (if present) to act as the "display name" of a deployment

**Comment by popen2** [comment]
What I'm thinking is to add a `display` feature to `features.yaml` which would look like:

```
apiVersion: platz.io/v1beta2
kind: Features
spec:
  display:
    name:
      InputField:
        name: alias
    icon:
      fontAwesome: rocket
```

With the current default being:

```
apiVersion: platz.io/v1beta2
kind: Features
spec:
  display:
    name:
      DeploymentName
    icon:
      fontAwesome: question
```
