### ISSUE TITLE
Optional number input of action, is passed as empty string and therefore fails on deserialization on deployment side

### ISSUE THREAD

**Issue by ayalash** [platzio/frontend#52]
Example for action definition:
```
apiVersion: platz.io/v1beta1
kind: Action
spec:
  id: my_parameters_action
  allowed_role: Maintainer
  endpoint: standard_ingress
  dangerous: true
  path: /api/v1/my_parameters_action
  method: POST
  title: Action with parameters
  description: This action will print message with passed parameters to stdout
  ui_schema:
    inputs:
      - id: required_number
        type: number
        label: Required number
        minimum: 0
        initialValue: 60000
        step: 1
        required: true
      - id: optional_number
        type: number
        label: Interval (ms)
        minimum: 0
        step: 1
    outputs:
      values:
        - path:
            - required_number
          value:
            FieldValue:
              input: required_number
        - path:
            - optional_number
          value:
            FieldValue:
              input: optional_number
```

After a single time of passing a value to `optional_number` there is no way to not passing.
